[2023-07-27T03:24:31.558+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:24:30.941106+00:00 [queued]>
[2023-07-27T03:24:31.564+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:24:30.941106+00:00 [queued]>
[2023-07-27T03:24:31.564+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-07-27T03:24:31.572+0000] {taskinstance.py:1327} INFO - Executing <Task(S3KeySensor): get_s3_id> on 2023-07-27 03:24:30.941106+00:00
[2023-07-27T03:24:31.576+0000] {standard_task_runner.py:57} INFO - Started process 8044 to run task
[2023-07-27T03:24:31.579+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgresv03', 'get_s3_id', 'manual__2023-07-27T03:24:30.941106+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_dependency.py', '--cfg-path', '/tmp/tmpv3s1ys78']
[2023-07-27T03:24:31.581+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask get_s3_id
[2023-07-27T03:24:31.617+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:24:30.941106+00:00 [running]> on host 93edf6c77c0f
[2023-07-27T03:24:31.671+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='richy' AIRFLOW_CTX_DAG_ID='dag_with_postgresv03' AIRFLOW_CTX_TASK_ID='get_s3_id' AIRFLOW_CTX_EXECUTION_DATE='2023-07-27T03:24:30.941106+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-27T03:24:30.941106+00:00'
[2023-07-27T03:24:31.672+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:24:31.681+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-07-27T03:24:31.682+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from extra.
[2023-07-27T03:24:36.961+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:24:41.987+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:24:47.006+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:24:52.019+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:24:57.051+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:25:02.074+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:25:02.097+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 30.42415572200116 seconds exceeds the specified timeout of 30.
[2023-07-27T03:25:02.116+0000] {taskinstance.py:1350} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_with_postgresv03, task_id=get_s3_id, execution_date=20230727T032430, start_date=20230727T032431, end_date=20230727T032502
[2023-07-27T03:25:02.132+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 15 for task get_s3_id (Sensor has timed out; run duration of 30.42415572200116 seconds exceeds the specified timeout of 30.; 8044)
[2023-07-27T03:25:02.200+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-27T03:25:02.216+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
