[2023-07-27T03:23:27.946+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:23:27.469214+00:00 [queued]>
[2023-07-27T03:23:27.952+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:23:27.469214+00:00 [queued]>
[2023-07-27T03:23:27.953+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-07-27T03:23:27.961+0000] {taskinstance.py:1327} INFO - Executing <Task(S3KeySensor): get_s3_id> on 2023-07-27 03:23:27.469214+00:00
[2023-07-27T03:23:27.964+0000] {standard_task_runner.py:57} INFO - Started process 7999 to run task
[2023-07-27T03:23:27.968+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgresv03', 'get_s3_id', 'manual__2023-07-27T03:23:27.469214+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_dependency.py', '--cfg-path', '/tmp/tmpcb7f30np']
[2023-07-27T03:23:27.970+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask get_s3_id
[2023-07-27T03:23:28.009+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:23:27.469214+00:00 [running]> on host 93edf6c77c0f
[2023-07-27T03:23:28.067+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='richy' AIRFLOW_CTX_DAG_ID='dag_with_postgresv03' AIRFLOW_CTX_TASK_ID='get_s3_id' AIRFLOW_CTX_EXECUTION_DATE='2023-07-27T03:23:27.469214+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-27T03:23:27.469214+00:00'
[2023-07-27T03:23:28.068+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:23:28.078+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-07-27T03:23:28.080+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from extra.
[2023-07-27T03:23:33.354+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:23:38.385+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:23:43.398+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:23:48.410+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:23:53.425+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:23:58.459+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:23:58.482+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 30.41332972300006 seconds exceeds the specified timeout of 30.
[2023-07-27T03:23:58.504+0000] {taskinstance.py:1350} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_with_postgresv03, task_id=get_s3_id, execution_date=20230727T032327, start_date=20230727T032327, end_date=20230727T032358
[2023-07-27T03:23:58.520+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 14 for task get_s3_id (Sensor has timed out; run duration of 30.41332972300006 seconds exceeds the specified timeout of 30.; 7999)
[2023-07-27T03:23:58.573+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-27T03:23:58.588+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
